server {
    listen 80;
    listen [::]:80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    location = /favicon.ico {
        try_files $uri =204;
        access_log off;
        log_not_found off;
    }

    location / {
        try_files $uri $uri.html $uri/ =404;
    }

    location ~ /\. {
        deny all;
        access_log off;
        log_not_found off;
    }
}